name: Validation
on: [push, pull_request]

jobs:
  supports-de-tp:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip' # caching pip dependencies
    - name: Install python libraries
      run: pip install -r requirements.txt
    - name: Run tp2-validation
      run: make tp2-validation